---
name: Test
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  # schedule: [{cron: '10 23 * * 1'}]  # M H d m w (Sat 23:10)
  workflow_dispatch:

jobs:

  ###########################
  test:
    if: github.event_name != 'pull_request' || !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association)
    name: Test ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: 'debian:bookworm'
            vendor: 'Debian'
            distro: 'bookworm'
          - container: 'debian:trixie'
            vendor: 'Debian'
            distro: 'trixie'
          - container: 'ubuntu:jammy'
            vendor: 'Ubuntu'
            distro: 'jammy'
          - container: 'ubuntu:noble'
            vendor: 'Ubuntu'
            distro: 'noble'
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - id: action
        uses: ./.github/..
        with:
          vendor: ${{ matrix.vendor }}
          distro: ${{ matrix.distro }}

  ###########################
  linter:
    if: github.event_name != 'pull_request' || !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association)
    runs-on: ubuntu-latest
    name: Executing Linters
    container: python:3.12
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - id: action_without_locales
        uses: ./.github/..
        with:
          manage_locales: false
      - uses: fbrehm/github-install-pip-modules@main
        with:
          install_linter_tools: true
      - name: Execute Yamllint
        shell: bash
        run: yamllint action.yml .github

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
